name: goku
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pyg
  - numpy
  - scipy
  - networkx
  - scikit-learn
  - matplotlib
  - pandas
  - tqdm
  - numba
  - pip:
    - attrdict
    - ogb
    - python-louvain
    - POT
    - networkit
    - wandb
    - umap-learn